### ISSUE TITLE
multiple config directory

### ISSUE THREAD

**Issue by gugansankar** [abh/geodns#64]
Is there any option to mention multiple configuration directory. ?. As I can add only one config directory using --config option. Sub directory json files are not loading. Else, Configuration has any include options like pgeodns. ? .

Reason behind is,  Easy to isolate the Customer zone files. Mean, I create a directory for each customers and put their zone files there. So its so easy to manage the configurations.

**Comment by abh** [comment]
Since the data is going to be loaded into the same namespace this doesn't really work. If you really need isolation because you can't trust the data then you need to run separate DNS instances (because the IPs need to be separated). If it's just to organize the files better then I'd suggest just having the files as you want them and a make job to copy them into one directory for syncing to your servers.
